### ISSUE TITLE
[Consent Manager] Transformer layer to work with REST API instead of GraphQL

### ISSUE THREAD

**Issue by karntrehan** [Konnect-Agri/consent-manager#17]

**Comment by amit-s19** [comment]
Depends on #28

**Comment by karntrehan** [comment]
KO APIs dont ask what elements are needed. They send everything in response. Need to connect with KO team to discuss consent manager implementation.

**Comment by karntrehan** [comment]
We will be building a gatekeeper on KO instead of baking CM into KO. 

Need authentication token to make KO work.

**Comment by karntrehan** [comment]
Working API received from CSM. V1 worked on from Amit.

**Comment by aashutosh-samagra** [comment]
Demo given by Amit. Action points -

**Comment by amit-s19** [comment]
Action Points After Demo : 
1. Make Consent manager more generic : Add support for both GQL and REST based inputs
2. Add API inputs in verify API body for REST based calls.

**Comment by karntrehan** [comment]
Dev testing to be done today along with code cleanup. PR to be raised.

**Comment by karntrehan** [comment]
PR raised. @ChakshuGautam to review.

**Comment by karntrehan** [comment]
Merged. To be deployed.
